# Generated by Django 6.0.6 on 2026-06-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.BinaryField()),
                ('slice', models.IntegerField(null=True)),
                ('file1', models.TextField(max_length=512)),
                ('file2', models.TextField(max_length=512, null=True)),
                ('display', models.IntegerField(choices=[(0, 'X'), (1, 'Y'), (2, 'Z')])),
                ('step', models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('slice', 'file1', 'display', 'step'), name='image_meta')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_data_issue', models.BooleanField(default=False, verbose_name='I suspect there might be a problem with the image quality')),
                ('comments', models.TextField(blank=True, default='', help_text='Please only add additional comments if necessary.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(0, 'Pass'), (1, 'Unsure'), (2, 'Fail')], default=None, verbose_name='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.image')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClickedCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_data_issue', models.BooleanField(default=False, verbose_name='I suspect there might be a problem with the image quality')),
                ('comments', models.TextField(blank=True, default='', help_text='Please only add additional comments if necessary.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.image')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
