# Generated by Django 6.0.6 on 2026-09-01 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, default='')),
                ('content_hash', models.TextField(unique=True)),
                ('toml', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit'), (5, 'T1w Coregistration')])),
                ('user', models.TextField(blank=True, default=None, null=True)),
                ('strategy', models.TextField(choices=[('breadth_first', 'Breadth First'), ('anomaly_first', 'Anomaly First')], default='breadth_first')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasuredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit'), (5, 'T1w Coregistration')])),
                ('file1', models.TextField(max_length=512)),
                ('entities', models.JSONField(blank=True, help_text="Categorical context for this file, e.g. {'space': 'MNI152NLin2009cAsym', 'res': '2'}. `manage prioritize` scores a metric within a subgroup of these.", null=True)),
                ('review_plan', models.ForeignKey(blank=True, help_text='The plan active when this file was measured.', null=True, on_delete=django.db.models.deletion.PROTECT, to='django_dirt_ratings.reviewplan')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', models.FileField(max_length=255, upload_to='')),
                ('digest', models.CharField(help_text='16-hex sha256 prefix of the stored image bytes. Names the media file (cache busting: new bytes, new URL) and lets the push client compare local and remote content without reading either file.', max_length=16)),
                ('slice', models.IntegerField(blank=True, null=True)),
                ('file1', models.TextField(max_length=512)),
                ('file2', models.TextField(blank=True, max_length=512, null=True)),
                ('display', models.IntegerField(choices=[(0, 'X'), (1, 'Y'), (2, 'Z')])),
                ('step', models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit'), (5, 'T1w Coregistration')])),
                ('n_reviews', models.PositiveIntegerField(default=0, help_text='Denormalized count of review submissions (Rating/Annotation rows) for this image, maintained by the services layer. Lets the review-ordering selector find the least-reviewed image with an index seek instead of an aggregate scan over every image of a step.')),
                ('priority', models.FloatField(blank=True, help_text='Advisory ordering key for the anomaly_first strategy, computed by `manage prioritize` as a robust within-subgroup modified z-score (MAD-based; |z| for two-sided measures). Larger = more atypical, surfaced earlier; 0.0 = typical (including a subgroup with no meaningful spread); NULL = no measure (sorts after scored images, i.e. breadth-first fallback). Only ever reorders — it never filters or hides an image.', null=True)),
                ('review_plan', models.ForeignKey(blank=True, help_text='The plan under which this image was rendered.', null=True, on_delete=django.db.models.deletion.PROTECT, to='django_dirt_ratings.reviewplan')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_data_issue', models.BooleanField(default=False, verbose_name='I suspect there might be a problem with the image quality')),
                ('comments', models.TextField(blank=True, default='', help_text='Please only add additional comments if necessary.')),
                ('rating', models.IntegerField(choices=[(0, 'Pass'), (1, 'Unsure'), (2, 'Fail')], verbose_name='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.image')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_data_issue', models.BooleanField(default=False, verbose_name='I suspect there might be a problem with the image quality')),
                ('comments', models.TextField(blank=True, default='', help_text='Please only add additional comments if necessary.')),
                ('grid_cols', models.IntegerField()),
                ('grid_rows', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.image')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnotationCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(0, 'Pass'), (1, 'Unsure'), (2, 'Fail')])),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='django_dirt_ratings.annotation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('annotation', 'col', 'row'), name='annotation_cell')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(help_text="The metric's canonical name: a `ComputedMetric` value for a metric DIRT computes, or a plan-declared `catalog` measure name.")),
                ('value', models.FloatField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='django_dirt_ratings.measuredfile')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'file'], name='metric_by_name')],
                'constraints': [models.UniqueConstraint(fields=('file', 'name'), name='metric_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='measuredfile',
            constraint=models.UniqueConstraint(fields=('step', 'file1'), name='measured_file'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['step', 'n_reviews', 'id'], name='image_next'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['step', 'n_reviews', '-priority', 'id'], name='image_priority'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('slice', 'file1', 'display', 'step'), name='image_meta'),
        ),
    ]
