# Generated by Django 6.0.6 on 2026-07-15 04:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit')])),
                ('user', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', models.BinaryField()),
                ('slice', models.IntegerField(blank=True, null=True)),
                ('file1', models.TextField(max_length=512)),
                ('file2', models.TextField(blank=True, max_length=512, null=True)),
                ('display', models.IntegerField(choices=[(0, 'X'), (1, 'Y'), (2, 'Z')])),
                ('step', models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit')])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('slice', 'file1', 'display', 'step'), name='image_meta')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_data_issue', models.BooleanField(default=False, verbose_name='I suspect there might be a problem with the image quality')),
                ('comments', models.TextField(blank=True, default='', help_text='Please only add additional comments if necessary.')),
                ('rating', models.IntegerField(choices=[(0, 'Pass'), (1, 'Unsure'), (2, 'Fail')], verbose_name='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.image')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_data_issue', models.BooleanField(default=False, verbose_name='I suspect there might be a problem with the image quality')),
                ('comments', models.TextField(blank=True, default='', help_text='Please only add additional comments if necessary.')),
                ('grid_cols', models.IntegerField()),
                ('grid_rows', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.image')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dirt_ratings.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnotationCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(0, 'Pass'), (1, 'Unsure'), (2, 'Fail')])),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='django_dirt_ratings.annotation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('annotation', 'col', 'row'), name='annotation_cell')],
            },
        ),
    ]
