# Generated by Django 6.0.7 on 2026-07-15 15:15

from django.db import migrations, models
from django.db.models import Count, OuterRef, Subquery
from django.db.models.functions import Coalesce

# Step values whose submissions are Annotations vs. Ratings (see models.Step).
ANNOTATION_STEPS = [0, 1, 2]  # MASK, SPATIAL_NORMALIZATION, SURFACE_LOCALIZATION
RATING_STEPS = [3, 4]  # FMAP_COREGISTRATION, DTIFIT


def backfill_n_reviews(apps, schema_editor):
    """Set n_reviews from existing submission counts (one UPDATE per step group)."""
    Image = apps.get_model("django_dirt_ratings", "Image")
    Annotation = apps.get_model("django_dirt_ratings", "Annotation")
    Rating = apps.get_model("django_dirt_ratings", "Rating")

    ann = (
        Annotation.objects.filter(image=OuterRef("pk"))
        .order_by()
        .values("image")
        .annotate(c=Count("id"))
        .values("c")
    )
    rat = (
        Rating.objects.filter(image=OuterRef("pk"))
        .order_by()
        .values("image")
        .annotate(c=Count("id"))
        .values("c")
    )
    Image.objects.filter(step__in=ANNOTATION_STEPS).update(
        n_reviews=Coalesce(Subquery(ann), 0)
    )
    Image.objects.filter(step__in=RATING_STEPS).update(
        n_reviews=Coalesce(Subquery(rat), 0)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('django_dirt_ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='n_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Denormalized count of review submissions (Rating/Annotation rows) for this image, maintained by the services layer. Lets the review-ordering selector find the least-reviewed image with an index seek instead of an aggregate scan over every image of a step.'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['step', 'n_reviews', 'id'], name='image_next'),
        ),
        migrations.RunPython(backfill_n_reviews, migrations.RunPython.noop),
    ]
