# Generated by Django 6.0.6 on 2026-07-16 03:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dirt_ratings', '0002_image_n_reviews_image_image_next'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, default='')),
                ('content_hash', models.TextField(unique=True)),
                ('toml', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.FloatField(blank=True, help_text='Advisory ordering key for the anomaly_first/triage strategies, computed by `manage prioritize` as a within-subgroup z-score (|z| for two-sided measures). Larger = more atypical, surfaced earlier; 0.0 = typical; NULL = no measure (sorts after scored images, i.e. breadth-first fallback). Only ever reorders — it never filters or hides an image.', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='raw_metrics',
            field=models.JSONField(blank=True, help_text="Measured values + rational-subgroup entities harvested at ingest, e.g. {'volume_mm3': 1.23e6, 'space': 'MNI152NLin2009cAsym'}. The source `manage prioritize` recomputes `priority` from.", null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='strategy',
            field=models.TextField(choices=[('breadth_first', 'Breadth First'), ('anomaly_first', 'Anomaly First'), ('triage', 'Triage')], default='breadth_first'),
        ),
        migrations.AddField(
            model_name='session',
            name='triage_depth',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='review_plan',
            field=models.ForeignKey(blank=True, help_text='The plan under which this image was rendered and measured.', null=True, on_delete=django.db.models.deletion.PROTECT, to='django_dirt_ratings.reviewplan'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['step', 'n_reviews', '-priority', 'id'], name='image_priority'),
        ),
    ]
