# Generated by Django 6.0.6 on 2026-08-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dirt_ratings', '0003_reviewplan_image_priority_image_raw_metrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.FloatField(blank=True, help_text='Advisory ordering key for the anomaly_first/triage strategies, computed by `manage prioritize` as a robust within-subgroup modified z-score (MAD-based; |z| for two-sided measures). Larger = more atypical, surfaced earlier; 0.0 = typical (including a subgroup with no meaningful spread); NULL = no measure (sorts after scored images, i.e. breadth-first fallback). Only ever reorders — it never filters or hides an image.', null=True),
        ),
    ]
