# Generated by Django 6.0.6 on 2026-08-30 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dirt_ratings', '0005_remove_session_triage_depth_alter_image_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='review_plan',
            field=models.ForeignKey(blank=True, help_text='The plan under which this image was rendered.', null=True, on_delete=django.db.models.deletion.PROTECT, to='django_dirt_ratings.reviewplan'),
        ),
        migrations.CreateModel(
            name='MeasuredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit')])),
                ('file1', models.TextField(max_length=512)),
                ('entities', models.JSONField(blank=True, help_text="Categorical context for this file, e.g. {'space': 'MNI152NLin2009cAsym', 'res': '2'}. `manage prioritize` scores a metric within a subgroup of these.", null=True)),
                ('review_plan', models.ForeignKey(blank=True, help_text='The plan active when this file was measured.', null=True, on_delete=django.db.models.deletion.PROTECT, to='django_dirt_ratings.reviewplan')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(help_text="The metric's canonical name: a `ComputedMetric` value for a metric DIRT computes, or a plan-declared `catalog` measure name.")),
                ('value', models.FloatField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='django_dirt_ratings.measuredfile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='measuredfile',
            constraint=models.UniqueConstraint(fields=('step', 'file1'), name='measured_file'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['name', 'file'], name='metric_by_name'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('file', 'name'), name='metric_name'),
        ),
    ]
