# Generated by Django 6.0.6 on 2026-08-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dirt_ratings', '0007_backfill_metrics_drop_raw_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='step',
            field=models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit'), (5, 'T1w Coregistration')]),
        ),
        migrations.AlterField(
            model_name='measuredfile',
            name='step',
            field=models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit'), (5, 'T1w Coregistration')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='step',
            field=models.IntegerField(choices=[(0, 'Mask'), (1, 'Spatial Normalization'), (2, 'Surface Localization'), (3, 'Fmap Coregistration'), (4, 'Dtifit'), (5, 'T1w Coregistration')]),
        ),
    ]
