[project]
name = "qcapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "connectorx>=0.4.2",
    "django>=5.1.6",
    "imageio>=2.37.0",
    "matplotlib>=3.10.0",
    "nibabel>=5.3.2",
    "nilearn>=0.11.1",
    "pillow>=11.1.0",
    "polars>=1.23.0",
    "pyarrow>=19.0.1",
    "pybids>=0.18.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
