"""
Django settings for qcapp project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import tempfile
from pathlib import Path


def strtobool(val):
    """Convert a string representation of truth to true (1) or false (0).

    True values are case insensitive 'y', 'yes', 't', 'true', 'on', and '1'.
    false values are case insensitive 'n', 'no', 'f', 'false', 'off', and '0'.
    Raises ValueError if 'val' is anything else.
    """
    val = val.lower()
    if val in ("y", "yes", "t", "true", "on", "1"):
        return 1
    elif val in ("n", "no", "f", "false", "off", "0"):
        return 0
    else:
        raise ValueError("invalid truth value %r" % (val,))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = strtobool(os.environ.setdefault("DJANGO_DEBUG", "False"))

ALLOWED_HOSTS = [
    ".localhost",
    "127.0.0.1",
    "[::1]",
    "0.0.0.0",
    "qcapp.pods.a2cps.tapis.io",
]


# Application definition

INSTALLED_APPS = [
    "django_qcapp_ratings",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_typer",
    "django_celery_results",
]

MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "qcapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "qcapp.wsgi.application"
ASGI_APPLICATION = "qcapp.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if strtobool(os.environ.get("DJANGO_DEPLOYED", "False")):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "postgres"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
            "HOST": "postgres.pods.a2cps.tapis.io",
            "PORT": 443,  # default postgres port
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.environ.get("DB", BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

if DEBUG:
    STATIC_URL = "static/"
else:
    # granian: matches --static-path-route
    STATIC_URL = "/static/"

    # granian: must be mounted with --static-path-mount
    STATIC_ROOT = BASE_DIR.parent / "static"
    # STATIC_ROOT = "/var/www/django/static"
    # MEDIA_ROOT = "/var/www/django/media"
    # STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = tempfile.mkdtemp()
MEDIA_URL = "/media/"


# https://docs.djangoproject.com/en/5.1/topics/logging/
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "timestamp": {"format": "%(asctime)s | %(levelname)-8s | %(message)s"}
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "timestamp"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

if strtobool(os.environ.get("DJANGO_DEPLOYED", "False")):
    SESSION_COOKIE_SECURE = True
    SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = ["https://qcapp.pods.a2cps.tapis.io"]
    # https://rtl.chrisadams.me.uk/2024/05/til-keeping-your-hair-when-upgrading-django-3-2-behind-a-caddy-server/
    # also needed because this is behind traefik
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True

# Celery Broker URL: Using RabbitMQ
# The standard AMQP URL for RabbitMQ, using default guest user and password,
# on localhost, default port 5672, and the default virtual host '/'.
CELERY_BROKER_URL = "amqp://guest:guest@localhost:5672//"


# Celery Result Backend: You can still use 'django-db' for convenience,
# or even RabbitMQ's RPC backend if you don't need persistent results.
# CELERY_RESULT_BACKEND = 'django-db' # Recommended for Django integration
# Alternatively, to use RabbitMQ itself for temporary, non-persistent results (RPC backend):
# CELERY_RESULT_BACKEND = "rpc://"
# Or, if you still want a persistent external cache:
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
# CELERY_WORKER_STATE_DB = None
CELERY_RESULT_BACKEND = "django-cache"
# CELERY_RESULT_BACKEND = "cache+memcached://127.0.0.1:11211/"
CELERY_CACHE_BACKEND = "default"

# Content type for tasks and results (JSON is still a good default)
# CELERY_ACCEPT_CONTENT = ["json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_RESULT_SERIALIZER = "json"

# Ensure this matches your Django TIME_ZONE if USE_TZ is True
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Optional: Time limit for tasks
# CELERY_TASK_SOFT_TIME_LIMIT = 300
# CELERY_TASK_TIME_LIMIT = 360

# Optional: Track 'STARTED' state
# CELERY_TASK_TRACK_STARTED = True

# Optional: Store errors even if results are otherwise ignored
# CELERY_TASK_STORE_ERRORS_EVEN_IF_IGNORED = True

# Optional: Configuration for django-celery-results
# DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH = 191

# Optional: Broker connection retry on startup (useful if broker starts after worker)
# CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# CELERY_WORKER_POOL = "gevent"


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
        "LOCATION": "unix:/tmp/memcached.sock",
    }
}

# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
#     }
# }
