#!/bin/bash
#SBATCH -J qcapp-fmap
#SBATCH -o fmap.log
#SBATCH -t 2-00:00:00
#SBATCH -p corralextra
#SBATCH -N 1 -n 1
#SBATCH -A A2CPS

set -xeu

a2cps=/corral-secure/projects/A2CPS
release=${a2cps}/products/consortium-data/pre-surgery-release-3-0-0/mris

pixi run b2t2 index \
	--output fmriprep.parquet \
	--workers 4 \
	"${release}"/derivatives/fmriprep

pixi run b2t2 index \
	--output synthstrip.parquet \
	--workers 4 \
	"${release}"/derivatives/synthstrip

apptainer run \
	--bind /scratch/08266/psadil/qcapp/fmriprep.parquet:/tmp/fmriprep.parquet \
	--bind "${a2cps}" \
	--env-file=.env \
	docker://psadil/qcapp:manage \
	add_fmap_coregistration \
	--update \
	/tmp/fmriprep.parquet &

apptainer run \
	--bind "${a2cps}" \
	--env-file=.env \
	docker://psadil/qcapp:manage \
	add_dtifit \
	--update \
	"${release}"/derivatives/qsirecon_fsl_dtifit/dtifit/multishell &

apptainer run \
	--bind /scratch/08266/psadil/qcapp/synthstrip.parquet:/tmp/synthstrip.parquet \
	--bind "${a2cps}" \
	--env-file=.env \
	docker://psadil/qcapp:manage \
	add_masks \
	--update \
	/tmp/synthstrip.parquet &

apptainer run \
	--bind "${a2cps}" \
	--env-file=.env \
	docker://psadil/qcapp:manage \
	add_surface_localization \
	--update \
	"${release}"/derivatives/freesurfer &

wait
